In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
data = load_iris(as_frame=True)
df = data.frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
df.shape

(150, 5)

In [5]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='str')

In [7]:
X = df.drop(columns="target") # X has 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', and 'petal width (cm)'
y = df["target"] # y has 'target' - what kind of Iris flower it is.

In [8]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=40
)

In [11]:
X_train.shape

(120, 4)

In [12]:
X_test.shape

(30, 4)

In [14]:
y_train.shape

(120,)

In [15]:
y_test.shape

(30,)

**Classification** predicts a category or class. **Regression** predicts a continuous numerical value. For the Iris dataset, we need classification because the target is categorical.

In [10]:
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

1.0

load_iris(): 
Loads the iris data.

as_frame=True: 
Loads the data in a dataframe format.

X: 
Features used to make predictions.

y: 
The target the model is trying to predict.

train_test_split: 
Separates data used for training from unseen data used for evaluation.

model.fit(): 
Learns patterns from the training data.

model.predict(): 
Uses the trained model to predict new data.

**Review**

What is a feature?
- A feature is an input variable used by the model to make predictions.

What is a target?
- A target is the value that the model is trying to predict.

What does model.fit() do?
- model.fit() trains the model by learning patterns and relationships from the training data.

Why do we split data into training and test sets?
- We need a training set to train the model, and we need test sets so we have fresh data to the model to evaluate the performance.

What does model.predict() do?
- model.predict() uses a trained model to make predictions on new input data.

What is data leakage?
- Data leakage happens when information that should not be available during prediction is used to train the model.